# Generated by Django 3.1.7 on 2021-03-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dep', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre_dep'],
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reg', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre_reg'],
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mun', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.departamentos')),
            ],
            options={
                'ordering': ['nombre_mun'],
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.regiones'),
        ),
    ]
