# Generated by Django 3.1.7 on 2021-04-23 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dep', models.CharField(max_length=100, unique=True)),
                ('mapa', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre_dep'],
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mun', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.departamentos')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre_mun'],
            },
        ),
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reg', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre_reg'],
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.municipios')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.negocios')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queja', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(default=datetime.datetime(2021, 4, 22, 22, 25, 4, 674196))),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.sucursales')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.regiones'),
        ),
    ]
