# Generated by Django 3.1.7 on 2021-03-29 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_neg', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['nombre_neg'],
            },
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['nombre_dep'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'ordering': ['nombre_mun'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='regiones',
            options={'ordering': ['nombre_reg'], 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.municipios')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.negocios')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queja', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('creacion', models.DateField(default=datetime.datetime(2021, 3, 28, 23, 6, 15, 83652))),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='denuncias.sucursales')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'ordering': ['creacion'],
            },
        ),
    ]
