# Generated by Django 3.1.7 on 2021-04-14 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_auto_20210328_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quejas',
            options={'verbose_name': 'Queja', 'verbose_name_plural': 'Quejas'},
        ),
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 12, 44, 35, 880493)),
        ),
    ]
