# Generated by Django 3.1.7 on 2021-04-15 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_auto_20210414_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocios',
            options={'ordering': ['nombre'], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.RenameField(
            model_name='negocios',
            old_name='nombre_neg',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 21, 1, 7, 627603)),
        ),
    ]
