# Generated by Django 3.1.7 on 2021-04-15 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_auto_20210414_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocios',
            options={'ordering': ['nombre'], 'verbose_name': 'negocio', 'verbose_name_plural': 'negocios'},
        ),
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 21, 8, 45, 882533)),
        ),
    ]
