# Generated by Django 3.1.7 on 2021-04-18 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_auto_20210417_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 20, 51, 37, 981931)),
        ),
    ]
