# Generated by Django 3.1.7 on 2021-04-19 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0010_auto_20210417_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 12, 58, 9, 239777)),
        ),
    ]
