# Generated by Django 3.1.7 on 2021-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0011_auto_20210419_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(),
        ),
    ]
