# Generated by Django 3.1.7 on 2021-04-21 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0012_auto_20210421_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 28, 19, 208363)),
        ),
    ]
