# Generated by Django 3.1.7 on 2021-04-21 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0013_auto_20210421_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
