# Generated by Django 3.1.7 on 2021-04-21 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0014_auto_20210421_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 34, 48, 326524)),
        ),
    ]
