# Generated by Django 3.1.7 on 2021-04-21 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0015_auto_20210421_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 19, 18, 24, 988432, tzinfo=utc)),
        ),
    ]
