# Generated by Django 3.1.7 on 2021-04-21 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0016_auto_20210421_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 19, 23, 58, 804520)),
        ),
    ]
