# Generated by Django 3.1.7 on 2021-04-22 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0017_auto_20210421_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 16, 58, 54, 833480)),
        ),
    ]
