# Generated by Django 3.1.7 on 2021-04-23 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0018_auto_20210422_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejas',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 21, 3, 8, 760388)),
        ),
    ]
